export const STATUS_RUNNING = 'STATUS_RUNNING';
export const STATUS_PAUSED = 'STATUS_PAUSED';
export const STATUS_NOT_STARTED = 'STATUS_NOT_STARTED';
export const STATUS_OVER = 'STATUS_OVER';

export const STATUS_ACTIONS = {
  RUNNING: STATUS_RUNNING,
  PAUSEDL: STATUS_PAUSED,
  NOT_STARTED: STATUS_NOT_STARTED,
  OVER: STATUS_OVER,
};
